package ru.pulsedoma.issues;

// FR-ISS-005, FR-ISS-009, FR-ISS-010, AC-15
public enum IssueStatus {
    DRAFT, OPEN, ASSIGNED, IN_PROGRESS, RESOLVED, VERIFICATION_72H,
    CLOSED_CONFIRMED, CLOSED_UNCONFIRMED, REVIEW_REQUIRED, REOPENED, WITHDRAWN, REJECTED
}
